### ISSUE TITLE
[enhancement] Better explanation/documentation of Connection -> Ping Settings

### ISSUE THREAD

**Issue by plantroon** [ubergeek42/weechat-android#549] opened 2022-09-05 11:49 UTC
I turned off this functionality and the app seems to continue working fine (sends notifications just fine, connection done via Websocket SSL).  What exactly is the purpose of this option? Is it to circumvent Android's power saving mechanisms or to actually save power better? I set all the apps I get from f-droid to unrestricted in battery optimization - does this option still make sense for me in any way?

**Comment by mhoran** [comment] 2022-09-05 13:16
The purpose of ping is for connection keepalive and disconnect detection. Some internet providers may sever long lived TCP connections if no data has been sent over them. The ping functionality keeps this from happening. In addition, there's no way for the app to know if a connection is dropped without sending a ping. So the ping is sent at a user specified interval to detect whether the connection has been dropped.

**Comment by plantroon** [comment] 2022-09-05 13:33
I started fiddling around with it because my app started disconnecting without actually being disconnected - no reconnect attempts are made, only I cannot receive/send messages. When I swipe through buffers, some of them have yellow mark on the send button. Without manually clicking disconnect and reconnect it won't recover. I am not sure if a recent update could have caused this or if it's due to my home network changes. In any case, the server side did not change at all so I am wondering why it started happening.

**Comment by oakkitten** [comment] 2022-09-05 15:42
Yellow badge means we are waiting for the server to send us lines. If it stays it means that either server is sending us those but we are not receiving them, or that the server did not get our request in the first place. You may want to try commands such as `/relay`, `/relay raw` for some insight. If you are using a reverse proxy or something, you might want to look at its logs. You can try connecting using different connection methods that the app is offering to see if some are more problematic. If you think that a recent update made things worse, please try an earlier version and tell us if it works better. Ultimately, this kind of a problem happens from time to time and sometimes it's so hard to figure out the root cause.

If all else fails, you may want to tweak ping settings to be more aggressive to force reconnection sooner.

**Comment by plantroon** [comment] 2022-09-07 20:38
It happened between the second and third <CENSORED MSG>
```
2022-09-07 15:32:00     <-- [1] weechat obj: 576 bytes, id: _nicklist_diff
2022-09-07 15:32:09     <-- [1] weechat obj: 378 bytes, id: _buffer_line_added
2022-09-07 15:32:11     --> [1] weechat input 0x5582482ea0b0 <CENSORED MSG>
2022-09-07 15:32:11     <-- [1] weechat obj: 356 bytes, id: _buffer_line_added
2022-09-07 15:32:11     <-- [1] weechat obj: 438 bytes, id: _buffer_line_added
2022-09-07 15:32:11     <-- [1] weechat obj: 303 bytes, id: _nicklist_diff
2022-09-07 15:32:16     --> [1] weechat input 0x5582482ea0b0 <CENSORED MSG>
2022-09-07 15:32:16     <-- [1] weechat obj: 366 bytes, id: _buffer_line_added
2022-09-07 15:32:17     <-- [1] weechat obj: 494 bytes, id: _buffer_line_added
2022-09-07 15:32:18     <-- [1] weechat obj: 432 bytes, id: _buffer_line_added
2022-09-07 15:32:19     <-- [1] weechat obj: 501 bytes, id: _buffer_line_added
2022-09-07 15:32:26     --> [1] weechat input 0x5582482ea0b0 <CENSORED MSG>
```
I may have switched access points during writing that third message, and that caused it. But this only affects Weechat in such disruptive way, I haven't seen even VOIP or video calls drop. I will continue debugging that relay (nginx in my case) to see what I can find.

**Comment by oakkitten** [comment] 2022-11-25 16:21
Sorry, this kind of got neglected.

On my device, Weechat-Android usually reconnects just fine when switching access points, but in some cases this may disrupt the connection in such a way that only frequent pinging can help. Without extensive investigation, I am not sure there's much we can do here, so I'm closing this. If anyone's got any concrete suggestions or alternative solutions, they are absolutely welcome.

**Closed by oakkitten** 2022-11-25 16:21 UTC
