### ISSUE TITLE
[Feature request] Add more line in the buffer

### ISSUE THREAD

**Issue by dummys** [ubergeek42/weechat-android#231] opened 2015-10-17 08:39 UTC
Hi, Is it possible to implement an option to srt the max length of the buffer? ike to have more than one day of chat,  becasuse it'annoying when you backlog and you can't see all the stuff.  thanks.

**Comment by oakkitten** [comment] 2015-10-17 14:36
duplicate of  #184

**Closed by oakkitten** 2015-10-17 14:36 UTC
Labels: duplicate
