### ISSUE TITLE
Option to stop enter from sending the type buffer

### ISSUE THREAD

**Issue by bangzek** [ubergeek42/weechat-android#566] opened 2023-03-11 02:42 UTC
My keyboard app MessagEase is so fast but really prone to typo and most of the time I ended up sending part and mistyped text because I tend to accidently touch the enter button. So if it not too much work,  having the option to stop automatically send when I hit enter is really gonna be helpful to me.

TIA

**Comment by oakkitten** [comment] 2023-03-18 17:17
This shouldn't be much work, someone just needs to sit down it and do it. So far no-one has volunteered though. 😔

This is a fair request but a duplicate of #524, so I'm closing this

**Closed** 2023-03-18 17:17 UTC
