### ISSUE TITLE
App does not work on Pixel 3 XL

### ISSUE THREAD

**Issue by wad209** [ubergeek42/weechat-android#403] opened 2018-10-20 11:50 UTC
Just got my Pixel 3 XL and weechat-android does not work. Just get stuck with the cat as shown here: https://linx.li/selif/vdgnqa95.png

Edit with a tiny bit more information: I tried a few things including reinstalling the app after clearing data and rebooting the phone. I also tried the nightly built with the same result.

**Comment by oakkitten** [comment] 2018-10-20 19:57
please try [getting](https://developer.android.com/studio/command-line/adb) the [debug logs](https://developer.android.com/studio/command-line/logcat). also there is [a light-theme branch](http://weechat-android.ubergeek42.com/index-light-theme.html) that's currently in development that uses newer libraries and works for me in the emulator, please try it. but we want the logs anyway. find us on irc (#weechat-android on freenode) if stuck

**Comment by AKPWebDesign** [comment] 2018-10-20 20:04
I'll work on helping get the debug logs (I was just about to open this issue myself as well). I started looking into why the app does this last night, but can't really seem to tell what's going on.

Basically, the app bar at the top (which looks like blank space in the screenshot @wad209 linked above) starts out very briefly on the screen, before appearing to slide up into the space occupied by the notification bar.

I'm pretty sure this is in some way related to the large notch on the Pixel 3 XL. Disabling the notch using the developer settings stops this issue from happening.

**Comment by wad209** [comment] 2018-10-20 20:54
I can confirm the light-theme works (and looks great!). I won't bother getting logs since @AKPWebDesign has already been so kind as to provide them!

**Comment by bmmiller** [comment] 2019-01-23 03:56
Is there anyway to get this fixed merged into master and pushed to the Play Store?

Don't really have a dev env for Android up and running so don't have a way to get the light-theme branch built to get an APK.

**Comment by AKPWebDesign** [comment] 2019-01-25 01:04
@bmmiller as far as I can tell, the link provided by @oakkitten above is the latest version of that branch. Still less ideal than if it were on the Play Store, but it's there and you don't have to build it.

**Comment by bmmiller** [comment] 2019-01-25 01:07
Yep, you're right. I missed that. Thanks.

**Comment by Tigge** [comment] 2019-02-25 13:47
The menu doesn't scroll in correctly either on the light-theme branch or on master. Seems to be due to the notch. Can be seen in the emulator if you simulate a notch on a Pixel 2 XL.

**Comment by goofus** [comment] 2020-01-16 15:26
Same problem on Oneplus 7 Pro (Android 10, Oxygen OS 10.0.3GM21BA). Light theme "fixed" it.

**Comment by agargiulo** [comment] 2020-01-26 01:41
This is still an issue on Pixel 3XL for Android 10 (Using a simulated 3XL in Android Studio). It looks like it's related to the "cutout" (read: notch)

I also tried the `light-theme` branch but that branch doesn't seem to fix it (it still launches the dark theme version and still has issues around the notch so not sure if I did something wrong to test it out.

**Comment by oakkitten** [comment] 2020-01-26 20:39
i pushed 31514b540303aad6518e5a5ebdc55095ecc80d65 to the upcoming branch that should fix this issue once and for all. the problem seems to be that the 300 pixels that we were using for the height of the keyboard actually included the system bars, and on 3xl the height of them (higher than usual dpi + tall notch + 3 navigation buttons) exceeded this number. this also makes the app behave better, though not ideally, in split screen mode. hope the initial measurement is reliable...

**Comment by oakkitten** [comment] 2020-03-12 04:04
i believe v0.14 resolved this issue. please verify

**Comment by brianredbeard** [comment] 2020-03-21 23:53
@oakkitten To be clear, I missed the previous messages, but I just checked with 0288e13 (http://weechat-android.ubergeek42.com/weechat-master-0288e13.apk) 
 and confirmed that it's working.  Thanks so much!

:+1: :tada: :100:  :shipit:

**Comment by oakkitten** [comment] 2020-03-24 20:57
great, thanks

**Closed by oakkitten** 2020-03-24 20:57 UTC

**Comment by Fudster** [comment] 2020-08-13 11:37
Hi! OnePlus 7 pro here. 

I am having the same issue.

Light theme does "fix" it

**Comment by oakkitten** [comment] 2020-08-13 16:22
@Fudster the current version is 1.0, do you have the issue on 1.0?

**Comment by Fudster** [comment] 2020-08-13 23:33
> @Fudster the current version is 1.0, do you have the issue on 1.0?

Yeah. I had a issue on the Android market app.

But after downloading the light theme linked above it works.

**Comment by oakkitten** [comment] 2020-08-14 00:05
i don't think Play Store has 1.0. are you sure it was 1.0?

**Comment by Fudster** [comment] 2020-08-14 00:48
> i don't think Play Store has 1.0. are you sure it was 1.0?


Yeah I have no idea what version the playstore app is. 

It doesn't say. It's just a blank screen with the kitty.
