### ISSUE TITLE
app breaks when attempting gssapi-with-mic login

### ISSUE THREAD

**Issue by sirpengi** [ubergeek42/weechat-android#237] opened 2015-11-05 10:06 UTC
I'm getting a crash with sshtunnel when the ssh server is configured to allow GSSAPIAuthentication.
This is on a Nexus 7 (Android 6.0) running WeechatAndroid 0.10-dev (build ID v0.10-88-g71fb7cf).  I have this same problem on my N5 phone as well.

For now my workaround is to disable this method on the server (`GSSAPIAuthentication=no` in sshd_config) but looking at the adb output it seems like there are missing libraries somewhere:

```
11-04 23:58:05.328 12207-24151/? I/System.out: [Level 1] Authentications that can continue: gssapi-with-mic,publickey,keyboard-interactive,password
11-04 23:58:05.328 12207-24151/? I/System.out: [Level 1] Next authentication method: gssapi-with-mic
11-04 23:58:05.402 12207-24151/? W/art: Unresolved exception class when finding catch block: org.ietf.jgss.GSSException
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime: FATAL EXCEPTION: Thread-649
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime: Process: com.ubergeek42.WeechatAndroid.dev, PID: 12207
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/ietf/jgss/Oid;
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:     at com.jcraft.jsch.jgss.GSSContextKrb5.a(Unknown Source)
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:     at com.jcraft.jsch.UserAuthGSSAPIWithMIC.a(Unknown Source)
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:     at com.jcraft.jsch.Session.a(Unknown Source)
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:     at com.ubergeek42.a.a.a.h.run(Unknown Source)
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818)
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:  Caused by: java.lang.ClassNotFoundException: Didn't find class "org.ietf.jgss.Oid" on path: DexPathList[[zip file "/data/app/com.ubergeek42.WeechatAndroid.dev-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ubergeek42.WeechatAndroid.dev-1/lib/arm, /vendor/lib, /system/lib]]
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:     at com.jcraft.jsch.jgss.GSSContextKrb5.a(Unknown Source) 
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:     at com.jcraft.jsch.UserAuthGSSAPIWithMIC.a(Unknown Source) 
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:     at com.jcraft.jsch.Session.a(Unknown Source) 
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:     at com.ubergeek42.a.a.a.h.run(Unknown Source) 
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818) 
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:  Suppressed: java.lang.ClassNotFoundException: org.ietf.jgss.Oid
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:     at java.lang.Class.classForName(Native Method)
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:          ... 6 more
11-04 23:58:05.403 12207-24151/? E/AndroidRuntime:  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
11-04 23:58:05.406 626-3910/? W/ActivityManager:   Force finishing activity com.ubergeek42.WeechatAndroid.dev/com.ubergeek42.WeechatAndroid.WeechatActivity
```

**Comment by oakkitten** [comment] 2015-11-05 16:46
i couldn't reproduce that, but:
https://stackoverflow.com/questions/28411153/jsch-suppressed-java-lang-classnotfoundexception-lorg-ietf-jgss-oid https://github.com/zeapo/Android-Password-Store/issues/49

**Comment by oakkitten** [comment] 2015-11-05 17:11
does the woah branch magically fix it perhaps? http://weechat-android.ubergeek42.com.s3.amazonaws.com/index-woah.html

**Comment by wirewc** [comment] 2015-11-05 17:21
The link appears broken. I did not get time to run adb at home but what I
am seeing is either the networking portion is having a problem or the
config files are not being read in. When running a previous build (10-25)
of the woah branch a toast message pops up about settings.

**Comment by oakkitten** [comment] 2015-11-14 23:31
the link to woah should be working now and i changed the way the public key and the known hosts are loaded, as well as the error messages. can you tell me if the problem is still there? if it is, i guess we'll have to try applying the fix from that so link

**Comment by oakkitten** [comment] 2020-08-05 15:58
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.

**Closed by oakkitten** 2020-08-05 15:58 UTC
