### ISSUE TITLE
Crash report from google play version(prefixlength = "")

### ISSUE THREAD

**Issue by ubergeek42** [ubergeek42/weechat-android#154] opened 2014-10-27 13:49 UTC
Looks like a bad preference setting(prefix length = ""), but it prevents the app from running I think. This is all the details I have.
```
java.lang.RuntimeException: Unable to create service com.ubergeek42.WeechatAndroid.service.RelayService: java.lang.NumberFormatException: Invalid int: ""
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2568)
at android.app.ActivityThread.access$1800(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5001)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NumberFormatException: Invalid int: ""
at java.lang.Integer.invalidInt(Integer.java:137)
at java.lang.Integer.parseInt(Integer.java:358)
at java.lang.Integer.parseInt(Integer.java:331)
at com.ubergeek42.WeechatAndroid.service.RelayService.onCreate(Unknown Source)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2558)
... 10 more
```

**Comment by mhoran** [comment] 2015-02-16 04:27
Duplicate of #139.

**Closed by mhoran** 2015-02-16 04:27 UTC
Labels: bug
