### ISSUE TITLE
SSH does not work with ED25519-Key and will show wrong error message

### ISSUE THREAD

**Issue by RincewindsHat** [ubergeek42/weechat-android#278] opened 2016-03-21 19:36 UTC
Using a ED25519-OpenSSH-Key will provoke an error message: "Error: invalid privatekey:" + a short string. Although there is text on the key-file option (in the dev-version currently) which lists the possible types of keys, the error message is not helpful.

**Comment by glubsy** [comment] 2019-06-23 22:32
I keep hitting this problem too. I can't even find mention of this cryptic error message anywhere in the source code. 

But I have not been using an ed25519 key, only RSA. Very strange.

Reading `man ssh-keygen` I notice this must be a newer format which is not (yet?) compatible here:

> -o Causes ssh-keygen to save private keys using the new OpenSSH format rather than the more compatible PEM format.  The new format has increased resistance to brute-force password cracking but is not supported by versions of OpenSSH prior to 6.5.  Ed25519 keys always use the new private key format.

I also suspect this could be related to the "known_host" file being wrong somehow... I'm clueless.

**Comment by cmcsun** [comment] 2019-06-23 22:41
I get same error. Only way around this is to use RSA for ssh key for weechat-android

**Comment by glubsy** [comment] 2019-06-23 22:47
My RSA key was generated with `ssh-keygen -t rsa`, isn't that enough? 

Note that the short string after "invalid privatekey:" seems to be random everytime.

I suspect this might be an error in parsing the private key.

**Comment by JohnMaguire** [comment] 2020-04-21 22:50
Just wanted to say thanks for the `ssh-keygen -t rsa -m PEM` tip - that's working for me on OpenSSH 8.2p1.

**Comment by oakkitten** [comment] 2020-08-05 18:15
closing this as a duplicate of #438. we definitely should support ED25519

**Closed by oakkitten** 2020-08-05 18:15 UTC

**Comment by cmcsun** [comment] 2020-08-19 00:53
> closing this as a duplicate of #438. we definitely should support ED25519

second this
