### ISSUE TITLE
Cannot connect using SSL with domain name (especially on home network)

### ISSUE THREAD

**Issue by chopin2712** [ubergeek42/weechat-android#533] opened 2021-11-10 19:03 UTC
I don't think this is an issue with the app  but I would like to know what I did wrong here and if a config is necessary on the home network. If so it could be nice to add it into the docs.

## Env
* **Android version** : 9
* **Weechat-Android** : v1.7.1 (from F-Droid)

### Setting the SSL relay up
I've setup an SSL relay on a remote Weechat instance. Here are the commands I used to generate the certificate:

```bash
mkdir -p ~/.weechat/ssl
sudo cat /etc/letsencrypt/live/DOMAIN.NAME/{fullchain,privkey}.pem > ~/.weechat/ssl/relay.pem
sudo chown -R $USER:$USER ~/.weechat/ssl/
```

Then those are the commands I used on Weechat:

```
/set relay.network.password y0ur_StRonG-pa$sw0rd:of*choice
/relay sslcertkey
/relay add ssl.weechat 9002
```

Those instructions are coming directly from the *Glowing Bear* website. Note that this is using the domain name instead of the IP. Because as far as I remember, **it works with IP as shown in your docs, but not with the domain as shown here**. 

## The problem
The problem happens when I try to connect to it from my home network. I enter the domain name, port, password, etc into the app and it says 

```
Error: failed to connect to DOMAIN.NAME/IPV6 (port 9002) from /IPV6 (port 53590) after 5000ms
```

Then I enable mobile data services and reconnect, and it works.

## How it's supposed to be working
I think it should work with domain name, from home network I don't see why it has to either be an IP or be done from mobile data services. 

Do I have to open specific ports for it? If so, why didn't I have to do that when connecting using IP instead of the domain?

**Comment by chopin2712** [comment] 2021-11-10 19:07
Edit, now I cannot make it work with mobile data either (?)

**Comment by oakkitten** [comment] 2021-11-16 17:29
if the connection works when you are using mobile data (i.e. connecting from WAN) but not when using wifi (i.e. connecting from LAN), the issue is probably your router not doing NAT loopback (aka hairpinning).

you have enable it on your router, or, if it doesn't do that, you might have to run your own DNS server to have the domain point to the LAN ip of the server instead of its WAN ip.

**Comment by oakkitten** [comment] 2021-12-25 21:53
closing because no reply

**Closed by oakkitten** 2021-12-25 21:53 UTC
Labels: needs info
