### ISSUE TITLE
Badly formatted "known hosts" cause cryptic "invalid base64 data" error during connection

### ISSUE THREAD

**Issue by dset0x** [ubergeek42/weechat-android#344] opened 2017-03-14 09:19 UTC
As titled. Either pasting badly formatted known hosts should not be allowed, or this error should be transformed to something more descriptive.

```
03-12 10:40:48.702  9241 14448 E RelayService: connect(): exception while creating connection
03-12 10:40:48.702  9241 14448 E RelayService: com.jcraft.jsch.JSchException: fromBase64: invalid base64 data
03-12 10:40:48.702  9241 14448 E RelayService: 	at com.jcraft.jsch.Util.fromBase64(Util.java:63)
03-12 10:40:48.702  9241 14448 E RelayService: 	at com.jcraft.jsch.KnownHosts.setKnownHosts(KnownHosts.java:218)
03-12 10:40:48.702  9241 14448 E RelayService: 	at com.ubergeek42.weechat.relay.connection.SSHConnection.<init>(SSHConnection.java:2337)
03-12 10:40:48.702  9241 14448 E RelayService: 	at com.ubergeek42.WeechatAndroid.service.RelayService.connect$12927d31(RelayService.java:229)
03-12 10:40:48.702  9241 14448 E RelayService: 	at com.ubergeek42.WeechatAndroid.service.RelayService.access$100$27b44e36(RelayService.java:48)
03-12 10:40:48.702  9241 14448 E RelayService: 	at com.ubergeek42.WeechatAndroid.service.RelayService$1$1.run(RelayService.java:158)
03-12 10:40:48.702  9241 14448 E RelayService: 	at com.ubergeek42.WeechatAndroid.service.RelayService$1.run(RelayService.java:178)
03-12 10:40:48.702  9241 14448 E RelayService: 	at android.os.Handler.handleCallback(Handler.java:751)
03-12 10:40:48.702  9241 14448 E RelayService: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-12 10:40:48.702  9241 14448 E RelayService: 	at android.os.Looper.loop(Looper.java:154)
03-12 10:40:48.702  9241 14448 E RelayService: 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-12 10:40:48.702  9241 14448 E RelayService: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=29; index=29
03-12 10:40:48.702  9241 14448 E RelayService: 	at com.jcraft.jsch.Util.fromBase64(Util.java:51)
03-12 10:40:48.702  9241 14448 E RelayService: 	... 10 more
03-12 10:40:48.702  9241 14448 E RelayService: onException(JSchException)
```

**Comment by smaslennikov** [comment] 2018-09-07 21:04
I have the same issue here.

**Comment by smaslennikov** [comment] 2018-09-08 17:56
I was running ConnectBot: SSHd to a machine, ran `ssh-keyscan host && echo` (because selecting text in it was off by a few characters, so I ended on the newline), copied the entire output. That's it

**Comment by dset0x** [comment] 2018-09-08 18:00
This bug is about the error message being non-informative.

**Comment by daviddever** [comment] 2020-04-12 23:09
> I was running ConnectBot: SSHd to a machine, ran `ssh-keyscan host && echo` (because selecting text in it was off by a few characters, so I ended on the newline), copied the entire output. That's it

Did the exact same thing and ran into the same issue, but I think the issue is with selecting the text in Connectbot is splitting up what should be one line into multiple lines. 

![2020-04-12 16-05-49](https://user-images.githubusercontent.com/7231988/79082035-93573400-7cd7-11ea-87aa-c6130b2d6f2f.png)

should be

```
# insomnia247.nl:22 SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
# insomnia247.nl:22 SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
insomnia247.nl ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCiakqV8uskOCerTiKFTtNDrTjUmq1lhgHcJet1LnQonoXvMuBV5tX3j5yiS4GCaJSvzcuaQjH1iZnyZP2CJmia0ukqwqbYp+NmTCExIvW4YQjG7CGNWqYAHhlskChp1NpNBYg4Q++LTmN34ZL7IbVYLUEo+wShW92RoJuDeVXxp6QvIer4OpCRNw0rnnFuDTN/5LrvZ7Wo13NaJeBIu5wsAowkIV1Z2cuo0PcMdfFoFj7FuvipSk9uf2aIGu4LU/eI5WSuvZjUbzjcBIOGsBSRV5TL0VJzbvFYGQtQdis+pnbLl8IhB2ZNBBn6XSxx83dFvIUbRWHG0yYDLjd5metZ
# insomnia247.nl:22 SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
insomnia247.nl ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBP5lDoqk00Fr1g6A5nUxKlC4Lc1tQj2ozi4eA+CaiAAic6GcQ+u4uDiMP32xOtbKOroC4INl7x/Cb3gzrlc+XhI=
```

Sorry since this is more user error, but maybe will help someone who is searching the error.

**Comment by oakkitten** [comment] 2020-08-05 20:48
also if you put complete garbage into known hosts, instead of bad base64, you get `Error: reject HostKey: <host>` which isn't quite helpful either. perhaps this could be resolved by switching to a new library as suggested in #438

**Closed** 2020-09-21 22:41 UTC
Labels: bad error message, enhancement
