### ISSUE TITLE
Crash in 1.7.1 from F-Droid

### ISSUE THREAD

**Issue by jspricke** [ubergeek42/weechat-android#525] opened 2021-07-16 14:36 UTC
Just got this when opening a channel for the first time on WA:
```
07-16 16:08:07.203  6739  7186 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
07-16 16:08:07.268 12400 12400 V BF      : proceeding!
07-16 16:08:09.161 12400 12400 V MainPagerAdapter: adding
07-16 16:08:09.163 12400 12400 V MainPagerAdapter: detaching
07-16 16:08:09.163 12400 12400 V BF      : proceeding!
07-16 16:08:09.169  4703  6373 W ShortcutService: reportShortcutUsed: package com.ubergeek42.WeechatAndroid doesn't have shortcut python.slack.XXX.%YYY.03e
07-16 16:08:09.206 12400 12400 V BF      : proceeding!
07-16 16:08:09.285 12400 31441 V RelayService: → onMessage("28")
07-16 16:08:09.289 12400 31441 V RelayService: → onMessage("nicklist")
07-16 16:08:09.292 12400 12400 V BF      : proceeding!
07-16 16:08:09.311 12400 12400 D AndroidRuntime: Shutting down VM
--------- beginning of crash
07-16 16:08:09.324 12400 12400 E AndroidRuntime: FATAL EXCEPTION: main
07-16 16:08:09.324 12400 12400 E AndroidRuntime: Process: com.ubergeek42.WeechatAndroid, PID: 12400
07-16 16:08:09.324 12400 12400 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 5(offset:-1).state:17 com.ubergeek42.WeechatAndroid.views.AnimatedRecyclerView{e41407a V.ED.V... ......ID 0,0-1080,1722 #7f090054 app:id/chat_lines}, adapter:com.ubergeek42.WeechatAndroid.adapters.ChatLinesAdapter@bc9d02b, layout:androidx.recyclerview.widget.LinearLayoutManager@e9cec88, context:com.ubergeek42.WeechatAndroid.WeechatActivity@4f9e700
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:133)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:102)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:59)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:7)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:35)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:10)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3157)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2614)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:726)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-16 16:08:09.324 12400 12400 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
07-16 16:08:09.329  4703 31678 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
07-16 16:08:09.340  4703  6373 W ActivityTaskManager:   Force finishing activity com.ubergeek42.WeechatAndroid/.WeechatActivity
07-16 16:08:09.380 12400 12400 I Process : Sending signal. PID: 12400 SIG: 9
07-16 16:08:09.405  4703  4718 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=33, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10193] ], android.os.BinderProxy@2a54ac)
07-16 16:08:09.406  4703  6164 W InputDispatcher: channel 'eb7283c com.ubergeek42.WeechatAndroid/com.ubergeek42.WeechatAndroid.WeechatActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-16 16:08:09.406  4703  6164 E InputDispatcher: channel 'eb7283c com.ubergeek42.WeechatAndroid/com.ubergeek42.WeechatAndroid.WeechatActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-16 16:08:09.408  4703  6313 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=33, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10193] ] (release request)
07-16 16:08:09.409  4703  8859 I WindowManager: WIN DEATH: Window{eb7283c u0 com.ubergeek42.WeechatAndroid/com.ubergeek42.WeechatAndroid.WeechatActivity}
07-16 16:08:09.411  4703  4719 I ActivityManager: Process com.ubergeek42.WeechatAndroid (pid 12400) has died: fore TOP 
07-16 16:08:09.412  4703  8859 W InputDispatcher: Attempted to unregister already unregistered input channel 'eb7283c com.ubergeek42.WeechatAndroid/com.ubergeek42.WeechatAndroid.WeechatActivity (server)'
07-16 16:08:09.413  6739  6739 V KeyguardUpdateMonitor: onSubscriptionInfoChanged()
07-16 16:08:09.416  6739  6739 V KeyguardUpdateMonitor: SubInfo:{id=1, iccId=8949228161533310286 simSlotIndex=0 carrierId=1454 displayName=Drillisch carrierName=Drillisch nameSource=4 iconTint=-16746133 mNumber= dataRoaming=0 iconBitmap=android.graphics.Bitmap@fd74e20 mcc 262 mnc 07mCountryIso=de isEmbedded false nativeAccessRules null cardString=8949228161533310286 cardId=-1 isOpportunistic false mGroupUUID=null mIsGroupDisabled=false profileClass=-1 ehplmns = [] hplmns = [26207, 26207] subscriptionType=0 mGroupOwner=null carrierConfigAccessRules=null}
07-16 16:08:09.417  4703  4719 W ActivityManager: Scheduling restart of crashed service com.ubergeek42.WeechatAndroid/.service.RelayService in 1000ms
07-16 16:08:09.437  4703  4952 I libprocessgroup: Successfully killed process cgroup uid 10193 pid 12400 in 30ms
07-16 16:08:09.446  4325  4325 I Zygote  : Process 12400 exited due to signal 9 (Killed)
07-16 16:08:09.452  4703  4834 W ActivityManager: setHasOverlayUi called on unknown pid: 12400
07-16 16:08:09.464  4703  8837 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.android.launcher3:10094?v=9&cv=14 pkg=com.google.android.googlequicksearchbox } U=0: not found
07-16 16:08:09.484  7016  8911 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
07-16 16:08:09.502  6739  6739 D ImageWallpaper: wallpaper visibility changes to: true
07-16 16:08:09.506  6739  6750 I ndroid.systemu: NativeAlloc concurrent copying GC freed 13639(702KB) AllocSpace objects, 11(220KB) LOS objects, 49% free, 6288KB/12MB, paused 94us total 146.236ms
07-16 16:08:09.846  4703  4834 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{8131ed6 u0 com.ubergeek42.WeechatAndroid/.WeechatActivity t-1 f}
07-16 16:08:10.446  4703  4719 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.ubergeek42.WeechatAndroid/.WeechatActivity bnds=[32,83][286,376]} from uid 10094
07-16 16:08:10.477  4325  4325 D Zygote  : Forked child process 31703
07-16 16:08:10.480  4703  4947 I ActivityManager: Start proc 31703:com.ubergeek42.WeechatAndroid/u0a193 for service {com.ubergeek42.WeechatAndroid/com.ubergeek42.WeechatAndroid.service.RelayService}
07-16 16:08:10.490  4703  4703 V SettingsProvider: Notifying for 0: content://settings/secure/reminder_exp_learning_time_elapsed
07-16 16:08:10.491  4703  4838 E system_server: Invalid ID 0x00000000.
07-16 16:08:10.551  4703  7118 W ActivityTaskManager: Request to remove task ignored for non-existent task 7655
07-16 16:08:10.574  4703  4946 E NotificationService: Suppressing notification from package by user request.
```

**Comment by oakkitten** [comment] 2021-07-21 13:47
a duplicate of #512 but not exactly, let's handle it there

**Closed by oakkitten** 2021-07-21 13:47 UTC
