### ISSUE TITLE
Notification disappears without being checked regardless of whether the notification tray has been opened.

### ISSUE THREAD

**Issue by ghost** [ubergeek42/weechat-android#191] opened 2015-02-24 07:57 UTC
I notice this a lot. I get a lot of PMs which show up in the top bar, then when I pull down to look at them I sometimes see them disappearing before I get to look at them, or disappearing after I've closed the pull down tray. Sometimes they behave and stay put, but usually they disappear too in less than a minute.

I think they disappear without extending the notification area, but I only notice this when I turn the screen on to check notifications, so they're displayed anyhow.

**Comment by zamabe** [comment] 2015-02-24 07:59
Stock Android 5.0.1, Nexus 5. I am experiencing the memory leak bug, so will try to remember to give an update on you'd when 5.1 finally lands

**Comment by mhoran** [comment] 2015-02-24 18:44
I would not be surprised if this were due to the memory leak bug, as I've seen similar behavior but only since upgrading my Nexus 5 to Android 5.0.1. There are other issues on Android 5.0, so hopefully we'll see some fixes soon.

**Comment by zamabe** [comment] 2015-03-11 19:01
Android 5.1. `v0.9-rc1-34-g684ce65` notifications appears to behave just fine :)

**Comment by zamabe** [comment] 2015-08-24 18:15
Still occurring regularly. Have seen it on 5.1.1 clean install and upgrade install. Device memory is normal when this happens.

**Comment by mhoran** [comment] 2015-08-25 00:29
I've seen this as well, since the Material Design changes were applied. I think some regression was introduced as a result.

**Comment by oakkitten** [comment] 2015-08-25 13:35
this might be relevant for some users.

weechat-android is checking the hotlist every 5 minutes or so; if you have a highlight on a buffer in weechat-android and the buffer is read in weechat, the highlight vanishes and so does the notification. mind that if the buffer is currently open in weechat, then you will still get notification on your phone, but as this highlight doesn't make it to the hotlist, next synchronization will remove the notification.

**Comment by oakkitten** [comment] 2020-08-05 15:59
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.

**Closed by oakkitten** 2020-08-05 15:59 UTC
