### ISSUE TITLE
Weechat Android crashes as soon as I connect to weechat

### ISSUE THREAD

**Issue by bezerker** [ubergeek42/weechat-android#292] opened 2016-06-07 14:08 UTC
Fresh Nexus 6 phone running 6.0.1.  Connecting via ssh tunnel through weechat or direct (using juicessh to provide the ssh tunnel) causes a crash as soon as i connect.  I don't see buffers or anything.

What should I do to debug?

**Comment by ubergeek42** [comment] 2016-06-07 14:17
Dupe of #279. I don't have android 6.0.1 to test/debug with myself.

If you're a developer, try to get logcat running and maybe build the application from source so it'll have more debug information in it.

**Closed by ubergeek42** 2016-06-07 14:17 UTC

**Comment by bezerker** [comment] 2016-06-07 16:00
Ah, didn't realize this was a dupe. Thanks for the link. I'll look at it.
