### ISSUE TITLE
Cannot see messages correctly through relay instance on Termux localhost

### ISSUE THREAD

**Issue by yusi1** [ubergeek42/weechat-android#562] opened 2023-02-13 02:40 UTC
I am unable to see messages correctly inside a Weechat relay instance that is running on my Android phone on localhost through a Linux emulation app called Termux, I am able to connect to the Weechat relay instance through the app, but the messages come through wierdly and I can't switch buffers, and there's an icon of a cat biting through a cable.

- Termux Weechat version: 3.8

**Comment by oakkitten** [comment] 2023-02-13 22:20
That's supposed to be an icon of a cat that caught the LAN cable it was chasing, meaning that it's connected, so that's alright. Could you explain what you mean by “weirdly”, and how you can't switch buffers? If you don't see any buffers, it might because the server buffers are hidden by default, and you don't have any others. FWIW I do have WeeChat in Termux and it works fine with Weechat-Android.

**Comment by yusi1** [comment] 2023-02-14 05:18
I *am* able to connect *and* see buffers, but text inside the buffers don't show for me, and am also unable to issue any `/join` or `/part` commands.

It is a bit hard to explain so I attached a video:


https://user-images.githubusercontent.com/82241382/218645892-37e3fa24-8863-4779-ad69-9613fecfd6e6.mp4

**Comment by oakkitten** [comment] 2023-02-14 14:04
Thanks for the video. Well this is super weird. We shouldn't be crashing, you shouldn't see the cat in a buffer, and messages should get through... To clarify, if you say something like `/print foo` in a channel, is the problem that you don't see `foo` in Weechat-Android, or you don't see it in WeeChat either?

Could you also provide:
* app build ID (you can find it in Settings → About)
* your Android flavor/version and device model
* did you install the app from F-Droid or Play Store?
* crash information and any relevant portions of logcat. You can get that by [installing `adb`](https://developer.android.com/studio/command-line/adb) and running `adb logcat`. Look not only for errors but for warnings as well.

P.S. You can tap on the cat to connect/disconnect

**Comment by yusi1** [comment] 2023-02-14 15:21
Yeah, when I do something like `/print foo` or send a message and click the send button on the Weechat-Android app, I am unable to see anything in both the Weechat-Android app and the Weechat instance running inside Termux.

Here's more info:
- App Build ID: v1.8.1-0-g7b11324d
- Android Flavor/Version: OneUI, Android 13
- Device Model: Samsung A52s 5G
- I have tried both the Play Store version and the FDroid version, and they both have the same issue, the version I'm using in the video is the Play Store version.
- Here are bits of the logs from `adb logcat`, I didn't really know what I was looking for and looked for just errors and then just warnings, I opened the app and made it crash twice and recorded the warnings / errors that happened in the logs afterwards:
 - Warnings: http://ix.io/4o2C
 - Errors: http://ix.io/4o2G

**Comment by oakkitten** [comment] 2023-02-14 18:16
Thanks, this is very helpful. Hm, it seems that the app fails to parse buffer IDs somehow. `ViewHolder`'s `id` seems to be `-1` for all buffers, and we get that from the buffer pointer. That would explain why the messages don't get through. I am at loss why this would happen.

Can you give more info:
* What does `/v` say in WeeChat? My Termux version says, `WeeChat 3.8 [compiled on Jan 8 202 12:18:20]`
* What's the connection way and parameters, if any? (Plain, SSL, etc)?
* Is there anything peculiar/nonstandard about the setup that you can think of?

If I can't reproduce the problem, I guess the only thing we could do would be debugging. Or perhaps we can build an APK for you that would print additional information. Could you pop into our IRC channel on libera? #weechat-android

**Comment by yusi1** [comment] 2023-02-14 18:36
@oakkitten I am `yaslam` on IRC btw

**Comment by yusi1** [comment] 2023-02-14 20:33
@oakkitten Per our conversation on IRC, I have installed the debug build and ran the same commands to get the logs, here are the Warning and Error and Debug logs:
- Warning: http://ix.io/4o52
- Error: http://ix.io/4o53
- Debug: http://ix.io/4o54

**Comment by yusi1** [comment] 2023-02-15 02:45
I tested the latest debug APK build and everything now works!
FYI: This build is the one that works: https://s3.amazonaws.com/weechat-android.ubergeek42.com/weechat-bad-buffer-ids-e0a6bee.apk

**Comment by yusi1** [comment] 2023-02-15 18:33
Okay, so after further testing, when I do `/close` in a buffer or select `Close` in the menu after clicking on the three dots, sometimes a random buffer will go completely blanked out (i.e absolutely nothing will be shown in the buffer, not even the Weechat version), only after I swipe left/right a few times to switch buffer or select the blanked out buffer from the menu does the buffer show text again, but sometimes this doesn't work, and the buffer stays blank until I join a new channel.

Here's a video describing the odd behaviour:

https://user-images.githubusercontent.com/82241382/219120945-f808ca15-d30e-412d-b89f-bcd64747c761.mp4

**Comment by oakkitten** [comment] 2023-02-17 19:16
Thanks for the video, most helpful. Could you check if 91ffe115c613254c4a31238d6acd83c1b3b542fd resolves the issue for you?

**Comment by yusi1** [comment] 2023-02-18 10:21
> Thanks for the video, most helpful. Could you check if [91ffe11](https://github.com/ubergeek42/weechat-android/commit/91ffe115c613254c4a31238d6acd83c1b3b542fd) resolves the issue for you?

Yep, that seems to fix the issue

**Comment by yusi1** [comment] 2023-03-04 13:43
There is a new error I've been experiencing, when quitting weechat in Termux without disconnecting from it in the `weechat-android` app, raw buffer names get shown.

Here is a video describing the odd behaviour:

https://user-images.githubusercontent.com/82241382/222905765-f1cfad70-2e18-4130-9284-8276f7bcd7f9.mp4

**Comment by oakkitten** [comment] 2023-03-18 17:23
I'll look into it but this is probably not an issue. We are tracking WeeChat objects primarily by the pointers, since both the short and full buffer names are not stable. In cases when those are not available for one reason or another, we show the pointer since it's better to show something... I guess?

**Comment by metaphysicsIO** [comment] 2023-05-18 16:22
My friend in IRC, who doesn't have a github account, asked me to convey a message for them: "can some one please comment and request this patch be merged: https://github.com/ubergeek42/weechat-android/issues/562"

**Closed** 2024-02-02 14:44 UTC
Labels: bug
